local _gui = require("common._gui")
local def = require("common.def")
local util = require("common.util")
local layers = { button = "button" }

local buttons = {
    play = true,
    exit = true,
}
---@cast buttons table<string, ExtraNode>
local input_mapping = {
    [def.touch] = _gui.on_input_touch({ buttons }),
}

function init(self)
    msg.post(".", "acquire_input_focus")
    _gui.extrafy(buttons, layers.button)
end

on_input = util.on_input_map(input_mapping)
